### ISSUE TITLE
Avaliable work with jQuery ^3.0

### ISSUE THREAD

**Issue by tibezh** [jonataswalker/timepicker.js#30]
Library don't work with the jQuery ^3.0 version.
For example, I got an error: size() is not a function. Take a look for docs about [size()](https://api.jquery.com/size/) function.

**Comment by tibezh** [comment]
Wrong project, sorry
